yourName = input("What's your name? ")
yourFood = input("What's your favorite food? ")
yourMusic = input("What's your favorite music? ")
yourLocation = input("Where do you live? ")
print()
print("You are")
print(yourName)
print("You are probably hungry for")
print(yourFood)
print("and you're definitely getting your grove on to")
print(yourMusic)
print("living in the amazing")
print(yourLocation)
